= Kotlin Style Guides

Official? https://github.com/JetBrains/kotlin-web-site/blob/64218469db3f746ab1f4a1c4c569c21d654d665f/pages/docs/reference/coding-conventions.md

Adam Benet: https://github.com/ditn/KotlinStyleGuide

== CoyIM (via Ola Bini)

CoyIM - a safe and secure chat client

In Go!

"CoyIM is a new client for the XMPP protocol. It is built upon https://github.com/agl/xmpp-client and https://github.com/twstrike/otr3. It adds a graphical user interface and tries to be safe and secure by default. Our ambition is that it should be possible for even the most high-risk people on the planet to safely use CoyIM, without having to make any configuration changes.

To do this, we enable OTR by default, we default to use Tor and we will use the Tor Onion Service for a server if we know it, and also to use TLS and TLS certificates to verify the connection - no configuration necessary. The implementation is written in the Go language, to avoid many common types of vulnerabilities that come from using unsafe languages."

