= Ten Stars of Country Music

TEN STARS OF COUNTRY MUSIC https://m.dw.com/en/ten-stars-of-country-music/g-47463997

== Kacey Musgraves (born 1988)

There are many contemporary female voices in country, but only one who won best album of the year at the 2019 Grammys. Though she's considered a newcomer compared to other performing country singers like Carrie Underwood, Miranda Lambert and Shania Twain, Musgraves carries the hope of exporting modern country to Europe and beyond.

== Conway Twitty (1933-1993)

Long before country music was hip, Conway Twitty represented a generation of male singers who, with honky-tonk twang and tons of Brylcreem hair gel, managed to reach a wide-ranging audience with several chart-topping hits, including "Hello Darlin'." Twitty, whose real name was Harold Lloyd Jenkins, died in 1993, but his performances have been resurrected in several episodes of "Family Guy."

== Tammy Wynette (1942-1998)

She taught generations of women to always "Stand by Your Man," though her music also reflected themes of emancipation, self-sufficiency and "D-I-V-O-R-C-E" — decades before the #MeToo movement. Dubbed "The First Lady of Country," Wynette went on to become one of country music's biggest-selling female singers. She recorded and performed up until five years before her death.

== Johnny Cash (1932-2003)

The world of country as it is today would be unthinkable with the contributions that Johnny Cash made to the genre. Cash was a rebel who brought a certain Blues music sensitivity to country and didn't care much about success — despite selling over 90 million records. His signature songs include "I Walk the Line" and "Ring of Fire." Several posthumous albums have been released.

== Loretta Lynn (born 1932)

Many think of Loretta Lynn as the Grande Dame of country. After all, she's been in the biz for over 60 years. Known for her quick-witted lyrics and her down to earth attitude, Lynn is the most awarded female country recording artist of all time. Lynn champions women's rights in her music, singing about infidelity and even birth control. Her biggest hits include "Fist City" and "She's Got You."

== Willie Nelson (born 1933)

Willie Nelson is the free-wheeling persona who channels the spirit of many Texan urbanites. The octogenarian singer is known the world over for numbers like "On The Road Again" and his touching interpretation of Elvis Presley's "Always on My Mind." He is also a staunch activist for environmental issues and a proud Democrat, proving that country isn't only music for conservatives.

== Dolly Parton (born 1946)

An icon of country music, Dolly Parton has been on the scene for over 50 years. While her greatest hit might be "Jolene," few people outside of country circles realize that she penned "I Will Always Love You," which later became a global success for Whitney Houston. Parton even has her own theme park in Tennessee: Dollywood.

== George Strait (born 1952)

You might be kicked out of Texas if you say a bad word about George Strait. "King George" reigns supreme over the Lone Star State, where he was born, and its country scene. His music can be characterized as a return to traditional country from the mid-20th century but with a contemporary twist. Strait has more than 60 number one hits under his belt buckle, including "All My Ex's Live in Texas."

== Reba McEntire (born 1955)

Second only to Dolly Parton, Reba McEntire is considered a queen of country. The Oklahoma native launched her career in the mid-1970s, though she originally intended to become an elementary school teacher. Over time, the fiery redhead won over critics with hits like "You Lie" and "Fancy." In addition to winning countless Country Music Awards, McEntire is also an accomplished actress.

== Garth Brooks (born 1962)

Garth Brooks is the literal rock star of country singers, giving the genre a harder, yet sensitive edge. The hat-clad singer with the Takemine guitar will tug at your heart strings with narrative songs like "If Tomorrow Never Comes," while a track like "Friends in Low Places" still makes his fans laugh whenever it's played on the radio today — nearly three decades after he got started in country.

